/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Todos {
  completed: Generated<number>;
  created_at: Generated<Date | null>;
  id: Generated<number>;
  task: string;
}

export interface DB {
  todos: Todos;
}
